name: wedding_bellz
description: A new Flutter project.

version: 1.0.0+1


environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get:
  cloud_firestore:
  firebase_core: ^2.7.1
  flutter_lints: ^2.0.0
  firebase_auth: ^4.2.10
  intl: ^0.17.0
  fluttertoast: ^8.2.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

